spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://47.94.157.37:3306/movie?serverTimeZone=UTC&characterEncoding=UTF-8
    password: zy5201314.
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/
mybatis:
  mapper-locations: classpath:sql/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com:
      example:
        mapper: debug